[package]
name = "npm_rust_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli_select = "0.1.6"
execute = "0.2.13"
json = "0.12.4"
serde_json = "1.0.111"
